FriendshipBundle\Entity\FriendshipRequest:
  type: entity
  table: friendship_request
  uniqueConstraints:
    friendship_request_users_idx:
      unique: true
      columns: [ from_username, to_username ]
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    status:
      column: status
      type: integer
      options:
        default: 0
    fromUsername:
      column: from_username
      type: string
      length: 255
    toUsername:
      column: to_username
      type: string
      length: 255

  lifecycleCallbacks: {  }
