services:
  friendship.manager:
    class: FriendshipBundle\Manager\FriendshipManager
    arguments: [ @doctrine.orm.entity_manager ]
  friendship.twig.extension:
    class: FriendshipBundle\Twig\FriendshipTwigExtension
    arguments: [ @friendship.manager ]
    tags:
      - { name: 'twig.extension' }
